# test nixos config build
variables:
  USERNAME: "nsb"
  HOSTNAME: "odinson"

stages:
  - build

build_nixos_config:
  stage: build
  image: nixos/nix
  before_script:
    export NIX_CONFIG="experimental-features = nix-command flakes"
  script:
    - nix flake update
    - nix build .#nixosConfigurations.${HOSTNAME}.config.system.build.toplevel --dry-run
    - nix build .#homeConfigurations.${USERNAME}@${HOSTNAME}.activationPackage '.?submodules=1'
