# test nixos config build
variables:
  USERNAME: "nsb"
  HOSTNAME: "odinson"

stages:
  - build

build_nixos_config:
  stage: build
  image: nixos/nix
  script:
    - nix flake update
    - nixos-rebuild build --flake --dry-run .#${HOSTNAME}
    - nix build .#homeConfigurations.${USERNAME}@${HOSTNAME}
