format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$rust\
$character"""

palette = "gruvbox_dark"

[directory]
style = "bright-black"

[character]
success_symbol = "[❯](color_yellow)"
error_symbol = "[❯](color_orange)"
vimcmd_symbol = "[❮](color_aqua)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "yellow"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "green"

[rust]
symbol = ""
style = "green"
format = '[$symbol( $version) ]($style)'

[palettes.gruvbox_dark]
color_fg0 = '#d4be98'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#7daea3'
color_aqua = '#89b482'
color_green = '#a9b665'
color_orange = '#e78a4e'
color_purple = '#d3869b'
color_red = '#ea6962'
color_yellow = '#d8a657'
