export EDITOR=nvim 
bindkey -v

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

# aliases
alias v="nvim"
alias vi="nvim"
alias vim="nvim"
alias activate='source .venv/bin/activate'
alias ls="eza --icons"
alias vf='nvim "$(fzf)"'
alias ll="ls -l"
alias lg="lazygit"
alias gs="git status"

cf() {
  local dir
  dir=$(fd . -type d 2> /dev/null | fzf) && cd "$dir"
}

# go
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

eval "$(gh copilot alias -- zsh)"
